
server:
  port: 8084

spring:
  profiles:
    include:
    - db

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**

custom:
  path:
    upload-images: 'c://uploadImages/'

