server:
  port: 8080
#  servlet:
#    context-path: /
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

spring:
  profiles:
    include:
      - db
      - oauth
      - images


  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**

  #custom:
  #  path:
  #    upload-images: 'c://uploadImages/'
  mail:
    host: smtp.gmail.com
    port: 465
    username: ghdi95@gmail.com
    password: jonggu1247~
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            required: true
          auth: true


