
server:
  port: 8080

spring:
  profiles:
    include:
      - db
      - oauth


  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**

#custom:
#  path:
#    upload-images: 'c://uploadImages/'

#OAuth2 Client Config
